# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Интерфейс_QT5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SteelRat(object):
    def setupUi(self, SteelRat):
        SteelRat.setObjectName("SteelRat")
        SteelRat.setEnabled(True)
        SteelRat.resize(1147, 705)

        self.pushButton = QtWidgets.QPushButton(SteelRat)
        self.pushButton.setGeometry(QtCore.QRect(280, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(SteelRat)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 630, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(SteelRat)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 630, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(SteelRat)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 630, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(SteelRat)
        self.pushButton_5.setGeometry(QtCore.QRect(730, 630, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")

        self.textBrowser = QtWidgets.QTextBrowser(SteelRat)
        self.textBrowser.setGeometry(QtCore.QRect(90, 80, 961, 431))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.graphicsView = QtWidgets.QGraphicsView(SteelRat)
        self.graphicsView.setGeometry(QtCore.QRect(-5, 1, 1151, 701))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.graphicsView.setFont(font)
        self.graphicsView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setInputMethodHints(QtCore.Qt.ImhNone)
        self.graphicsView.setObjectName("graphicsView")
        self.fontComboBox = QtWidgets.QFontComboBox(SteelRat)
        self.fontComboBox.setGeometry(QtCore.QRect(10, 0, 71, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.label = QtWidgets.QLabel(SteelRat)
        self.label.setGeometry(QtCore.QRect(50, 620, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setTabletTracking(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.graphicsView.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.fontComboBox.raise_()
        self.label.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(SteelRat)
        QtCore.QMetaObject.connectSlotsByName(SteelRat)

    def retranslateUi(self, SteelRat):
        _translate = QtCore.QCoreApplication.translate
        SteelRat.setWindowTitle(_translate("SteelRat", "STEEl RAT"))
        self.pushButton.setText(_translate("SteelRat", "Кнопка 1"))
        self.pushButton_2.setText(_translate("SteelRat", "Кнопка 2"))
        self.pushButton_3.setText(_translate("SteelRat", "Кнопка 3"))
        self.pushButton_4.setText(_translate("SteelRat", "Кнопка 4"))
        self.pushButton_5.setText(_translate("SteelRat", "Кнопка 5"))
        self.label.setText(_translate("SteelRat", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SteelRat = QtWidgets.QDialog()
    ui = Ui_SteelRat()
    ui.setupUi(SteelRat)
    SteelRat.show()
    sys.exit(app.exec_())
