# Generated by Django 4.1.7 on 2023-07-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='article_title_en_us',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='article_title_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='subscribers_en_us',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='subscribers_ru',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_author_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_author_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_title_en_us',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='article_title_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='news_category_en_us',
            field=models.ManyToManyField(null=True, through='simpleapp.NewsPortalCategory', to='simpleapp.newscategory'),
        ),
        migrations.AddField(
            model_name='newsportal',
            name='news_category_ru',
            field=models.ManyToManyField(null=True, through='simpleapp.NewsPortalCategory', to='simpleapp.newscategory'),
        ),
        migrations.CreateModel(
            name='NewsPortalCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newsportal')),
                ('news_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newscategory')),
            ],
            options={
                'verbose_name': 'news portal category [ru]',
                'verbose_name_plural': 'news portal categorys [ru]',
                'db_table': 'simpleapp_newsportalcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPortalCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newsportal')),
                ('news_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newscategory')),
            ],
            options={
                'verbose_name': 'news portal category [en-us]',
                'verbose_name_plural': 'news portal categorys [en-us]',
                'db_table': 'simpleapp_newsportalcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
