# Generated by Django 4.1.7 on 2023-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_newscategory_article_title_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='subscribers_en_us',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='subscribers_ru',
        ),
    ]
